baseURL = "https://blog.tsis-web.com/"
languageCode = "ja"
title = "t-sis blog"
theme = "jeffprod"
publishDir = "docs"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"